name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#   workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      LUA_PATH: src/?.lua;src/?/init.lua;luaunit/?.lua;luacov/src/?.lua;;
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Install Lua
        uses: leafo/gh-actions-lua@master
      - name: Install LuaUnit
        run: git clone https://github.com/bluebird75/luaunit.git
      - name: Install LuaCov
        run: git clone https://github.com/lunarmodules/luacov.git
      - name: Download SmartThings Lua Libraries 
        uses: robinraju/release-downloader@main
        with:
          repository: SmartThingsCommunity/SmartThingsEdgeDrivers
          latest: true
          fileName: lua_libs-api_*.tar.gz
      - name: Unpack SmartThings Lua Libraries 
        run: tar -xvzf lua_libs-api_*
      - name: Include SmartThings Lua Libraries into LUA_PATH
        run: echo "LUA_PATH=$(find lua_libs-api_* -type d -maxdepth 0 -printf "%p/?.lua;%p/?/init.lua;")$LUA_PATH" >> $GITHUB_ENV
      - name: Create env_secret.lua 
        run: |
          cat > src/env_secret.lua << EOF
            RouterUsername = '${{secrets.ROUTER_USERNAME}}'
            RouterPassword = '${{secrets.ROUTER_PASSWORD}}'
          EOF
      - name: Run tests
        run: lua -lluacov test/unit_tests.lua
      - name: Install html-xml-utils
        run: sudo apt-get install html-xml-utils
      - name: Check tests coverage
        run: "[ \"$(hxnormalize -l 240 -x luacov.report.html | hxselect -s '\n' -c 'body div.total span.cov strong')\" == \"100.0%\" ]"
      - name: Download SmartThings CLI
        uses: robinraju/release-downloader@main
        with:
          repository: SmartThingsCommunity/smartthings-cli
          latest: true
          fileName: smartthings-linux-x64.tar.gz
      - name: Unpack SmartThings CLI 
        run: tar -xvzf smartthings-linux-x64.tar.gz
      - name: Deploy driver
        run: ./smartthings edge:drivers:package -I -t=${{secrets.ST_PAM_TOKEN}} --channel=${{vars.ST_CHANNEL}}
