name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      LUA_PATH: src/?.lua:src/?/init.lua:luaunit/?.lua
    steps:
      - uses: actions/checkout@main
      - uses: leafo/gh-actions-lua@master
      - run: |
          git clone https://github.com/bluebird75/luaunit.git
          echo $LUA_PATH
