name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#   workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      LUA_PATH: src/?.lua;src/?/init.lua;luaunit/?.lua;luacov/src/?.lua;lua_libs-api_*/?.lua;lua_libs-api_*/?/init.lua;;
    steps:
      - uses: actions/checkout@main
      - uses: leafo/gh-actions-lua@master
      - run: git clone https://github.com/bluebird75/luaunit.git
      - run: git clone https://github.com/lunarmodules/luacov.git
      - uses: robinraju/release-downloader@main
        with:
          repository: SmartThingsCommunity/SmartThingsEdgeDrivers
          latest: true
          fileName: lua_libs-api_*.tar.gz
      - run: tar -xvzf lua_libs-api_*
      - run: |
          ls ../lua_libs-api_*
          TEST_PATH=$(find lua_libs-api_* -type d -maxdepth 0 -printf "%p/?.lua;%p/?/init.lua;")$LUA_PATH
          echo $TEST_PATH
#       - run: lua -lluacov test/unit_tests.lua
