name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#   workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      LUA_PATH: src/?.lua;src/?/init.lua;luaunit/?.lua;luacov/src/?.lua;;
    steps:
      - uses: actions/checkout@main
      - uses: leafo/gh-actions-lua@master
      - run: git clone https://github.com/bluebird75/luaunit.git
      - run: git clone https://github.com/lunarmodules/luacov.git
      - uses: robinraju/release-downloader@main
        with:
          repository: SmartThingsCommunity/SmartThingsEdgeDrivers
          latest: true
          fileName: lua_libs-api_*.tar.gz
      - run: tar -xvzf lua_libs-api_*
      - run: echo "LUA_PATH=$(find lua_libs-api_* -type d -maxdepth 0 -printf "%p/?.lua;%p/?/init.lua;")$LUA_PATH" >> $GITHUB_ENV
      - run: |
          cat > src/env_secret.lua << EOF
            RouterUsername = '${{secrets.ROUTER_USERNAME}}'
            RouterPassword = '${{secrets.ROUTER_PASSWORD}}'
          EOF
      - run: lua -lluacov test/unit_tests.lua
      - run: "[ \"$(hxnormalize -l 240 -x luacov.report.html | hxselect -s '\n' -c 'body div.total span.cov strong')\" == \"100.0%\" ] && echo 'true' || echo 'false'"
    
